// src/models/user.model.ts

export interface UserModel {
  id: string;            // UUID generated by DB
  email: string;         // user email
  passwordHash: string;  // hashed password stored in DB
  createdAt?: Date;
  updatedAt?: Date;
}
